version: '3.5'

services:

  distributed-task-postgresql:
    restart: always
    hostname: distributed-task-postgresql
    image: postgres:12.11-alpine
    command: postgres -c 'shared_preload_libraries=pg_stat_statements' -c 'pg_stat_statements.track=all' -c 'max_connections=100'
    environment:
      POSTGRES_USER: distributed-task
      POSTGRES_PASSWORD: distributed-task
      POSTGRES_DB: distributed-task
    stop_signal: SIGINT
